import { Test, TestingModule } from "@nestjs/testing";
import { <%= pascalCase %>sController } from "@modules/<%= kebabCase %>s.controller";<% if (moduleService) { %>
import { <%= pascalCase %>sService } from "@modules/<%= kebabCase %>s.service";<% } %><% if (moduleDto) { %>
import { Create<%= pascalCase %>Dto } from "@modules/dto/create-<%= kebabCase %>.dto";
import { Update<%= pascalCase %>Dto } from "@modules/dto/update-<%= kebabCase %>.dto";<% } %>
import { Response, Request } from "express";
import { ValidationError } from "class-validator";

describe("<%= pascalCase %>sController", () => {
	let controller: <%= pascalCase %>sController;<% if (moduleExtends) { %>
	let service: <%= pascalCase %>sService;

	const mock<%= pascalCase %> = {
		_id: "1"
	};

	const mock<%= pascalCase %>sService = {
		create: jest
			.fn()
			.mockImplementation((dto: Create<%= pascalCase %>Dto) =>
				Promise.resolve({ _id: "1", ...dto }),
			),
		findAll: jest.fn().mockResolvedValue([mock<%= pascalCase %>]),
		findOne: jest
			.fn()
			.mockImplementation((id: string) =>
				Promise.resolve({ _id: id, ...mock<%= pascalCase %> }),
			),
		update: jest
			.fn()
			.mockImplementation((id: string, dto: Update<%= pascalCase %>Dto) =>
				Promise.resolve({ _id: id, ...dto }),
			),
		remove: jest.fn().mockResolvedValue({ _id: "1", ...mock<%= pascalCase %> }),
	};

	function mockResponse(): Partial<Response> {
		const res: Partial<Response> = {
			status: jest.fn().mockReturnThis(),
			json: jest.fn().mockReturnThis(),
		};
		return res;
	}

	function mockRequest(customerId: string): Partial<Request> {
		return {
			customer: { _id: customerId },
		} as Partial<Request>;
	}

	beforeEach(async () => {
		const module: TestingModule = await Test.createTestingModule({
			controllers: [<%= pascalCase %>sController],
			providers: [
				{
					provide: <%= pascalCase %>sService,
					useValue: mock<%= pascalCase %>sService,
				},
			],
		}).compile();

		controller = module.get<<%= pascalCase %>sController>(<%= pascalCase %>sController);
		service = module.get<<%= pascalCase %>sService>(<%= pascalCase %>sService);
	});

	it("should be defined", () => {
		expect(controller).toBeDefined();
	});

	/*
	 * Create
	 */
	it("Create [201] - should create a <%= camelCase %>", async () => {
		const dto: Create<%= pascalCase %>Dto = {
		};

		const res = mockResponse() as Response;

		await controller.create(dto, res);

		expect(res.status).toHaveBeenCalledWith(201);
		expect(res.json).toHaveBeenCalledWith({
			code: 201,
			datas: { <%= camelCase %>s: { _id: "1", ...dto } },
			message: "<%= camelCase %>s create with success",
			success: true,
		});
		expect(service.create).toHaveBeenCalledWith(dto);
	});

	it("Create [422] - should handle validation errors when creating a <%= camelCase %>", async () => {
		const dto: Create<%= moduleName %>Dto = {
		};

		const validationError = new ValidationError();
		validationError.property = "PROPERTY";
		validationError.constraints = { VALIDATOR: "VALIDATOR MESSAGE" };

		jest.spyOn(service, "create").mockRejectedValueOnce([validationError]);

		const res = mockResponse() as Response;

		await controller.create(dto, res);

		expect(res.status).toHaveBeenCalledWith(422);
		expect(res.json).toHaveBeenCalledWith({
			code: 422,
			datas: { <%= camelCase %>s: [validationError] },
			message: "Validation errors occurred",
			success: false,
		});
		expect(service.create).toHaveBeenCalledWith(dto);
	});

	it("Create [500] - should handle internal server errors when creating a <%= camelCase %>", async () => {
		const dto: Create<%= moduleName %>Dto = {
		};

		jest.spyOn(service, "create").mockRejectedValueOnce(
			new Error("Internal server error"),
		);

		const res = mockResponse() as Response;

		await controller.create(dto, res);

		expect(res.status).toHaveBeenCalledWith(500);
		expect(res.json).toHaveBeenCalledWith({
			code: 500,
			datas: { <%= camelCase %>s: "Internal server error" },
			message: "An internal server error occurred",
			success: false,
		});
		expect(service.create).toHaveBeenCalledWith(dto);
	});

	/*
	 * FindAll
	 */
	it("FindAll [200] - should return all <%= camelCase %>s", async () => {
		const res = mockResponse() as Response;

		await controller.findAll(res);

		expect(res.status).toHaveBeenCalledWith(200);
		expect(res.json).toHaveBeenCalledWith({
			code: 200,
			datas: { <%= camelCase %>s: [mock<%= moduleName %>] },
			message: "<%= camelCase %>s retrieve with success",
			success: true,
		});
		expect(service.findAll).toHaveBeenCalled();
	});

	it("FindAll [404] - should handle not found error when returning all <%= camelCase %>s", async () => {
		jest.spyOn(service, "findAll").mockResolvedValueOnce([]);

		const res = mockResponse() as Response;

		await controller.findAll(res);

		expect(res.status).toHaveBeenCalledWith(404);
		expect(res.json).toHaveBeenCalledWith({
			code: 404,
			datas: { <%= camelCase %>s: "Not Found" },
			message: "<%= camelCase %>s not found",
			success: false,
		});
		expect(service.findAll).toHaveBeenCalled();
	});

	it("FindAll [500] - should handle internal server errors when returning all <%= camelCase %>s", async () => {
		jest.spyOn(service, "findAll").mockRejectedValueOnce(
			new Error("Internal server error"),
		);

		const res = mockResponse() as Response;

		await controller.findAll(res);

		expect(res.status).toHaveBeenCalledWith(500);
		expect(res.json).toHaveBeenCalledWith({
			code: 500,
			datas: { <%= camelCase %>s: "Internal server error" },
			message: "<%= camelCase %>s internal server error",
			success: false,
		});
		expect(service.findAll).toHaveBeenCalled();
	});

	/*
	 * FindOne
	 */
	it("FindOne [200] - should return a single <%= camelCase %> by id", async () => {
		const res = mockResponse() as Response;

		await controller.findOne("1", res);

		expect(res.status).toHaveBeenCalledWith(200);
		expect(res.json).toHaveBeenCalledWith({
			code: 200,
			datas: { <%= camelCase %>s: { _id: "1", ...mock<%= moduleName %> } },
			message: "<%= camelCase %>s retrieve with success",
			success: true,
		});
		expect(service.findOne).toHaveBeenCalledWith("1");
	});

	it("FindOne [404] - should handle not found error when returning a single <%= camelCase %> by id", async () => {
		jest.spyOn(service, "findOne").mockResolvedValueOnce(null);

		const res = mockResponse() as Response;

		await controller.findOne("1", res);

		expect(res.status).toHaveBeenCalledWith(404);
		expect(res.json).toHaveBeenCalledWith({
			code: 404,
			datas: { <%= camelCase %>s: "Not Found" },
			message: "<%= camelCase %>s not found",
			success: false,
		});
		expect(service.findOne).toHaveBeenCalledWith("1");
	});

	it("FindOne [500] - should handle internal server errors when returning a single <%= camelCase %> by id", async () => {
		jest.spyOn(service, "findOne").mockRejectedValueOnce(
			new Error("Internal server error"),
		);

		const res = mockResponse() as Response;

		await controller.findOne("1", res);

		expect(res.status).toHaveBeenCalledWith(500);
		expect(res.json).toHaveBeenCalledWith({
			code: 500,
			datas: { <%= camelCase %>s: "Internal server error" },
			message: "<%= camelCase %>s internal server error",
			success: false,
		});
		expect(service.findOne).toHaveBeenCalledWith("1");
	});

	/*
	 * Update
	 */
	it("Update [404] - should handle not found error when updating a <%= camelCase %> by id", async () => {
		const dto: Update<%= moduleName %>Dto = { PROPERTY: "VALUE" };

		jest.spyOn(service, "update").mockResolvedValueOnce(null);

		const res = mockResponse() as Response;

		await controller.update("1", dto, res);

		expect(res.status).toHaveBeenCalledWith(404);
		expect(res.json).toHaveBeenCalledWith({
			code: 404,
			datas: { <%= camelCase %>s: "Not Found" },
			message: "<%= camelCase %>s not found",
			success: false,
		});
		expect(service.update).toHaveBeenCalledWith("1", dto);
	});

	it("Update [500] - should handle internal server errors when updating a <%= camelCase %> by id", async () => {
		const dto: Update<%= moduleName %>Dto = { PROPERTY: "VALUE" };

		jest.spyOn(service, "update").mockRejectedValueOnce(
			new Error("Internal server error"),
		);

		const res = mockResponse() as Response;

		await controller.update("1", dto, res);

		expect(res.status).toHaveBeenCalledWith(500);
		expect(res.json).toHaveBeenCalledWith({
			code: 500,
			datas: { <%= camelCase %>s: "Internal server error" },
			message: "<%= camelCase %>s internal server error",
			success: false,
		});
		expect(service.update).toHaveBeenCalledWith("1", dto);
	});

	it("Update [422] - should handle validation errors when updating a <%= camelCase %> by id", async () => {
		const dto: Update<%= moduleName %>Dto = { PROPERTY: "VALUE" };

		const validationError = new ValidationError();
		validationError.property = "PROPERTY";
		validationError.constraints = {
			isString: "PROPERTY must be a string",
		};

		jest.spyOn(service, "update").mockRejectedValueOnce([validationError]);

		const res = mockResponse() as Response;

		await controller.update("1", dto, res);

		expect(res.status).toHaveBeenCalledWith(422);
		expect(res.json).toHaveBeenCalledWith({
			code: 422,
			datas: { <%= camelCase %>s: [validationError] },
			message: "Validation errors occurred",
			success: false,
		});
		expect(service.update).toHaveBeenCalledWith("1", dto);
	});

	/*
	 * Delete
	 */
	it("Delete [200] - should delete a <%= camelCase %> by id", async () => {
		const res = mockResponse() as Response;

		await controller.remove("1", res);

		expect(res.status).toHaveBeenCalledWith(200);
		expect(res.json).toHaveBeenCalledWith({
			code: 200,
			datas: { <%= camelCase %>s: { removed: true } },
			message: "<%= camelCase %>s delete with success",
			success: true,
		});
		expect(service.remove).toHaveBeenCalledWith("1");
	});

	it("Delete [404] - should handle not found error when deleting a <%= camelCase %> by id", async () => {
		jest.spyOn(service, "findOne").mockResolvedValueOnce(null);

		const res = mockResponse() as Response;

		await controller.remove("1", res);

		expect(res.status).toHaveBeenCalledWith(404);
		expect(res.json).toHaveBeenCalledWith({
			code: 404,
			datas: { <%= camelCase %>s: {} },
			message: "<%= camelCase %>s not found",
			success: false,
		});
		expect(service.findOne).toHaveBeenCalledWith("1");
	});

	it("Delete [500] - should handle internal server errors when deleting a <%= camelCase %> by id", async () => {
		jest.spyOn(service, "remove").mockRejectedValueOnce(
			new Error("Internal server error"),
		);

		const res = mockResponse() as Response;

		await controller.remove("1", res);

		expect(res.status).toHaveBeenCalledWith(500);
		expect(res.json).toHaveBeenCalledWith({
			code: 500,
			datas: { <%= camelCase %>s: "Internal server error" },
			message: "<%= camelCase %>s internal server error",
			success: false,
		});
		expect(service.remove).toHaveBeenCalledWith("1");
	});<% } %>
});
